language: node_js
node_js:
  - '0.8'
  - '0.10'

install:
  - gem install compass
  - npm install -g bower grunt-cli
  - bower install

script:
  - grunt test

after_success:
  - cat coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
