language: node_js
node_js:
  - '0.10'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - gem install compass
  - npm install -g bower grunt-cli
  - bower install -F

script:
  - grunt test

after_success:
  - cat coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
